/**
 * Volume Bot SDK Types
 */

// Bot configuration interface
export interface BotConfig {
  id: string
  symbol: string
  name: string
  address: string
  logo?: string
  minTradeAmount: number
  maxTradeAmount: number
  duration: number
  strategy: string
  platform: string
  tradesPerMinute: number
  numberOfWallets: number
  useAntiMev: boolean
  useFakeSigners: boolean
  useRepeatWallets: boolean
  tipAmount: number
  priorityFees: number
  slippage: number
  status?: "active" | "paused" | "stopped"
  progress?: number
}

// Bot status type
export type BotStatus = "active" | "paused" | "stopped"

// Trade type
export interface Trade {
  id: string
  botId: string
  walletAddress: string
  amount: number
  type: "buy" | "sell"
  timestamp: Date
  txHash?: string
  status: "pending" | "confirmed" | "failed"
  price?: number
}

// Wallet type
export interface Wallet {
  id: string
  address: string
  privateKey?: string // Only available for wallets generated by the SDK
  solBalance: number
  tokenBalance: number
  tradesCount: number
  lastTrade?: Date
  selected?: boolean
  tag?: string
}

// Log entry type
export interface LogEntry {
  id: string
  botId: string
  timestamp: Date
  message: string
  type: "info" | "success" | "warning" | "error"
  data?: any
}

// Event types
export type BotEvent =
  | { type: "bot:started"; botId: string; config: BotConfig }
  | { type: "bot:paused"; botId: string }
  | { type: "bot:stopped"; botId: string }
  | { type: "bot:deleted"; botId: string }
  | { type: "bot:progress"; botId: string; progress: number }
  | { type: "bot:error"; botId: string; error: string }
  | { type: "trade:executed"; botId: string; trade: Trade }
  | { type: "trade:failed"; botId: string; trade: Trade; error: string }
  | { type: "wallet:created"; botId: string; wallet: Wallet }
  | { type: "wallet:funded"; botId: string; wallet: Wallet; amount: number }
  | { type: "log:new"; botId: string; log: LogEntry }

// Event listener type
export type EventListener = (event: BotEvent) => void

// SDK Configuration
export interface SDKConfig {
  devWalletPrivateKey?: string
  fundingWalletPrivateKey?: string
  rpcUrl?: string
  jitoRegion?: string
  debug?: boolean
}
